on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test docker meta works
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Test action
      id: meta
      uses: ./
    - name: Get the output args
      run: echo "The time was ${{ steps.meta.outputs.build-args }}"

